import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  pl: {
    desktopApp: 'Aplikacja desktopowa', how: 'Jak to działa', noKey: 'Brak klucza API (Demo)', apiSettings: 'Ustawienia klucza API (BYOK)',
    kicker: 'Wyszukiwarka momentów w wideo', hero1: 'Zapytaj nagranie.', hero2: 'Znajdź właściwy kadr.', heroText: 'Wklej link YouTube lub dodaj własny plik. Opisz scenę, wypowiedź albo temat, a dostaniesz dokładny fragment.',
    youtubeFiles: 'YOUTUBE + PLIKI', natural: 'JĘZYK NATURALNY', precision: 'PRECYZJA DO SEKUNDY', youtubeLink: '01 / LINK YOUTUBE', pasteLink: 'Wklej link do filmu', directYoutube: 'Odtwarzanie bezpośrednio z YouTube', open: 'Otwórz', or: 'albo', diskFile: 'PLIK Z DYSKU', drop: 'Upuść nagranie lub wybierz plik', maxFile: 'MP4, WEBM, MP3, WAV · maks. 200 MB', demo: 'Demo',
    find: 'Znajdź moment & Odpowiedź AI', findSub: 'Agent AI przeczyta nagranie i odpowie na Twoje pytanie', searchPlaceholder: 'np. Czy Piastowie pochodzili ze Skandynawii?', clear: 'Wyczyść zapytanie', search: 'Szukaj', suggestions: 'Podpowiedzi', suggestion1: 'Czy Piastowie byli nordami?', suggestion2: 'Co badacz mówi o genetyce Słowian?', suggestion3: 'Jaki jest główny wniosek?', aiAssistant: 'ASYSTENT AI FILMU (RAG)', jump: 'Skocz do sekundy', basedAnswer: 'Odpowiedź na podstawie nagrania:', quote: 'Cytat z nagrania:', waiting: 'Materiał czeka na pytanie', analyzeFirst: 'Najpierw przeanalizuj nagranie', emptyHelp: 'Wpisz pytanie w języku naturalnym — Agent AI znajdzie moment i odpowie na pytanie w oparciu o cytaty.', related: 'Powiązane fragmenty wideo', playing: 'ODTWARZANIE', match: 'DOPASOWANIA', copyQuote: 'Kopiuj cytat ze znacznikiem czasu',
    utterances: 'wypowiedzi', ready: 'gotowy do analizy', removeMedia: 'Usuń plik / otwórz inny', demoMedia: 'Materiał demonstracyjny', teamTalk: 'rozmowa zespołu', loaded: 'Wczytano', showTranscript: 'Pełna transkrypcja', hideTranscript: 'Ukryj transkrypcję', fullRecord: 'Pełny zapis rozmowy', generate: 'Generuję transkrypcję', runTranscription: 'Uruchom transkrypcję', uploadSubs: 'Wgraj własny plik napisów (SRT / VTT)', usingKey: 'Używasz klucza API:', keyRequired: 'Wymagany klucz API do pełnej analizy nagrania.', configure: 'Skonfiguruj klucz API', timeline: 'Fragmenty na osi czasu', result: 'Wynik', playback: 'Odtwarzanie',
    workflow1: 'Dodaj link lub plik', workflow1s: 'YouTube, wideo lub audio', workflow2: 'Zadaj pytanie', workflow2s: 'Własnymi słowami', workflow3: 'Odtwórz scenę', workflow3s: 'Od właściwej sekundy', privacy: 'Prywatne nagrania. Precyzyjne odpowiedzi.',
    apiTitle: 'Ustawienia klucza API', chooseProvider: 'Wybierz dostawcę AI / Transkrypcji:', apiKey: 'Klucz API', hideKey: 'Ukryj klucz', showKey: 'Pokaż klucz', security: 'Twój klucz jest zapisywany wyłącznie w Twojej przeglądarce (localStorage). Nigdy nie jest przesyłany na żaden serwer pośredniczący.', deleteKey: 'Usuń klucz', useDemo: 'Używaj trybu Demo', testing: 'Testuję klucz...', saved: 'Zapisano!', chooseLocal: 'Wybierz transkrypcję lokalną', testSave: 'Testuj i zapisz klucz API', close: 'Zamknij',
    noKeyTitle: 'Brak skonfigurowanego klucza API', browserAnalysis: 'Przeglądarkowa analiza wideo / audio', noKeyText: 'Nie dodałeś jeszcze swojego klucza API. Możesz skorzystać z jednej z dwóch opcji:', optionDemo: 'Opcja 1: Przełącz w tryb Demo (Zalecane)', optionDemoText: 'Użyj wbudowanych danych demonstracyjnych, aby przetestować wyszukiwanie, znaczniki czasu i eksport SRT.', tryDemo: 'Wypróbuj w trybie Demo', optionKey: 'Opcja 2: Podaj swój klucz API', optionKeyText: 'Dodaj klucz OpenAI, Google Gemini lub Groq Cloud. Zostanie zapisany wyłącznie lokalnie w Twojej przeglądarce.'
  },
  en: {
    desktopApp: 'Desktop app', how: 'How it works', noKey: 'No API key (Demo)', apiSettings: 'API key settings (BYOK)',
    kicker: 'Video moment search engine', hero1: 'Ask your recording.', hero2: 'Find the right frame.', heroText: 'Paste a YouTube link or upload your own file. Describe a scene, quote, or topic to get the exact moment.',
    youtubeFiles: 'YOUTUBE + FILES', natural: 'NATURAL LANGUAGE', precision: 'SECOND-PRECISE', youtubeLink: '01 / YOUTUBE LINK', pasteLink: 'Paste a video link', directYoutube: 'Play directly from YouTube', open: 'Open', or: 'or', diskFile: 'FILE FROM DISK', drop: 'Drop a recording or choose a file', maxFile: 'MP4, WEBM, MP3, WAV · max. 200 MB', demo: 'Demo',
    find: 'Find a moment & AI answer', findSub: 'The AI agent reads the recording and answers your question', searchPlaceholder: 'e.g. What is the main conclusion?', clear: 'Clear query', search: 'Search', suggestions: 'Suggestions', suggestion1: 'What is the main topic?', suggestion2: 'What does the speaker say about the research?', suggestion3: 'What is the main conclusion?', aiAssistant: 'VIDEO AI ASSISTANT (RAG)', jump: 'Jump to time', basedAnswer: 'Answer based on the recording:', quote: 'Quote from the recording:', waiting: 'The recording is ready for a question', analyzeFirst: 'Analyze a recording first', emptyHelp: 'Ask a question in natural language — the AI agent will find the moment and answer using quotes.', related: 'Related video moments', playing: 'PLAYING', match: 'MATCH', copyQuote: 'Copy quote with timestamp',
    utterances: 'segments', ready: 'ready to analyze', removeMedia: 'Remove media / open another', demoMedia: 'Demo recording', teamTalk: 'team conversation', loaded: 'Loaded', showTranscript: 'Full transcript', hideTranscript: 'Hide transcript', fullRecord: 'Full transcript', generate: 'Generating transcript', runTranscription: 'Start transcription', uploadSubs: 'Upload your own subtitles (SRT / VTT)', usingKey: 'API provider:', keyRequired: 'An API key is required for full recording analysis.', configure: 'Configure API key', timeline: 'Moments on the timeline', result: 'Result', playback: 'Playback',
    workflow1: 'Add a link or file', workflow1s: 'YouTube, video, or audio', workflow2: 'Ask a question', workflow2s: 'In your own words', workflow3: 'Play the scene', workflow3s: 'From the exact second', privacy: 'Private recordings. Precise answers.',
    apiTitle: 'API key settings', chooseProvider: 'Choose an AI / transcription provider:', apiKey: 'API key', hideKey: 'Hide key', showKey: 'Show key', security: 'Your key is stored only in your browser (localStorage). It is never sent to an intermediary server.', deleteKey: 'Delete key', useDemo: 'Use Demo mode', testing: 'Testing key...', saved: 'Saved!', chooseLocal: 'Choose local transcription', testSave: 'Test and save API key', close: 'Close',
    noKeyTitle: 'No API key configured', browserAnalysis: 'Browser-based video / audio analysis', noKeyText: 'You have not added an API key yet. Choose one of these two options:', optionDemo: 'Option 1: Switch to Demo mode (Recommended)', optionDemoText: 'Use built-in demo data to test search, interactive timestamps, and SRT export.', tryDemo: 'Try Demo mode', optionKey: 'Option 2: Enter your API key', optionKeyText: 'Add an OpenAI, Google Gemini, or Groq Cloud key. It will be stored only in your browser.'
  },
  es: {
    desktopApp: 'Aplicación de escritorio', how: 'Cómo funciona', noKey: 'Sin clave API (Demo)', apiSettings: 'Configuración de la clave API (BYOK)',
    kicker: 'Buscador de momentos en vídeo', hero1: 'Pregunta a tu grabación.', hero2: 'Encuentra el fotograma adecuado.', heroText: 'Pega un enlace de YouTube o sube tu propio archivo. Describe una escena, una frase o un tema para obtener el momento exacto.',
    youtubeFiles: 'YOUTUBE + ARCHIVOS', natural: 'LENGUAJE NATURAL', precision: 'PRECISIÓN AL SEGUNDO', youtubeLink: '01 / ENLACE DE YOUTUBE', pasteLink: 'Pega el enlace del vídeo', directYoutube: 'Reproducir directamente desde YouTube', open: 'Abrir', or: 'o', diskFile: 'ARCHIVO DEL DISCO', drop: 'Suelta una grabación o elige un archivo', maxFile: 'MP4, WEBM, MP3, WAV · máx. 200 MB', demo: 'Demo',
    find: 'Encuentra un momento y obtén una respuesta de IA', findSub: 'El agente de IA lee la grabación y responde a tu pregunta', searchPlaceholder: 'p. ej., ¿Cuál es la conclusión principal?', clear: 'Borrar consulta', search: 'Buscar', suggestions: 'Sugerencias', suggestion1: '¿Cuál es el tema principal?', suggestion2: '¿Qué dice el ponente sobre la investigación?', suggestion3: '¿Cuál es la conclusión principal?', aiAssistant: 'ASISTENTE DE VÍDEO CON IA (RAG)', jump: 'Ir al momento', basedAnswer: 'Respuesta basada en la grabación:', quote: 'Cita de la grabación:', waiting: 'La grabación está lista para una pregunta', analyzeFirst: 'Analiza primero una grabación', emptyHelp: 'Haz una pregunta en lenguaje natural: el agente de IA encontrará el momento y responderá usando citas.', related: 'Momentos relacionados del vídeo', playing: 'REPRODUCIENDO', match: 'COINCIDENCIA', copyQuote: 'Copiar cita con marca de tiempo',
    utterances: 'segmentos', ready: 'listo para analizar', removeMedia: 'Eliminar contenido / abrir otro', demoMedia: 'Grabación de demostración', teamTalk: 'conversación del equipo', loaded: 'Cargado', showTranscript: 'Transcripción completa', hideTranscript: 'Ocultar transcripción', fullRecord: 'Transcripción completa', generate: 'Generando transcripción', runTranscription: 'Iniciar transcripción', uploadSubs: 'Sube tus propios subtítulos (SRT / VTT)', usingKey: 'Proveedor de API:', keyRequired: 'Se necesita una clave API para analizar toda la grabación.', configure: 'Configurar clave API', timeline: 'Momentos en la línea de tiempo', result: 'Resultado', playback: 'Reproducción',
    workflow1: 'Añade un enlace o archivo', workflow1s: 'YouTube, vídeo o audio', workflow2: 'Haz una pregunta', workflow2s: 'Con tus propias palabras', workflow3: 'Reproduce la escena', workflow3s: 'Desde el segundo exacto', privacy: 'Grabaciones privadas. Respuestas precisas.',
    apiTitle: 'Configuración de la clave API', chooseProvider: 'Elige un proveedor de IA / transcripción:', apiKey: 'Clave API', hideKey: 'Ocultar clave', showKey: 'Mostrar clave', security: 'Tu clave se guarda únicamente en tu navegador (localStorage). Nunca se envía a un servidor intermediario.', deleteKey: 'Eliminar clave', useDemo: 'Usar modo Demo', testing: 'Probando clave...', saved: '¡Guardado!', chooseLocal: 'Elegir transcripción local', testSave: 'Probar y guardar la clave API', close: 'Cerrar',
    noKeyTitle: 'No hay ninguna clave API configurada', browserAnalysis: 'Análisis de vídeo / audio en el navegador', noKeyText: 'Aún no has añadido una clave API. Elige una de estas dos opciones:', optionDemo: 'Opción 1: Cambiar al modo Demo (Recomendado)', optionDemoText: 'Usa los datos de demostración incluidos para probar la búsqueda, las marcas de tiempo interactivas y la exportación SRT.', tryDemo: 'Probar el modo Demo', optionKey: 'Opción 2: Introducir tu clave API', optionKeyText: 'Añade una clave de OpenAI, Google Gemini o Groq Cloud. Se guardará únicamente en tu navegador.'
  },
  de: {
    desktopApp: 'Desktop-App', how: 'So funktioniert es', noKey: 'Kein API-Schlüssel (Demo)', apiSettings: 'API-Schlüssel-Einstellungen (BYOK)',
    kicker: 'Suchmaschine für Videomomente', hero1: 'Frag deine Aufnahme.', hero2: 'Finde den richtigen Moment.', heroText: 'Füge einen YouTube-Link ein oder lade eine eigene Datei hoch. Beschreibe eine Szene, ein Zitat oder ein Thema und erhalte den genauen Moment.',
    youtubeFiles: 'YOUTUBE + DATEIEN', natural: 'NATÜRLICHE SPRACHE', precision: 'SEKUNDENGENAU', youtubeLink: '01 / YOUTUBE-LINK', pasteLink: 'Videolink einfügen', directYoutube: 'Direkt von YouTube abspielen', open: 'Öffnen', or: 'oder', diskFile: 'DATEI VOM COMPUTER', drop: 'Aufnahme ablegen oder Datei auswählen', maxFile: 'MP4, WEBM, MP3, WAV · max. 200 MB', demo: 'Demo',
    find: 'Moment finden & KI-Antwort', findSub: 'Der KI-Agent liest die Aufnahme und beantwortet deine Frage', searchPlaceholder: 'z. B. Was ist die wichtigste Schlussfolgerung?', clear: 'Suchanfrage löschen', search: 'Suchen', suggestions: 'Vorschläge', suggestion1: 'Was ist das Hauptthema?', suggestion2: 'Was sagt der Sprecher über die Forschung?', suggestion3: 'Was ist die wichtigste Schlussfolgerung?', aiAssistant: 'VIDEO-KI-ASSISTENT (RAG)', jump: 'Zum Zeitpunkt springen', basedAnswer: 'Antwort auf Grundlage der Aufnahme:', quote: 'Zitat aus der Aufnahme:', waiting: 'Die Aufnahme ist bereit für eine Frage', analyzeFirst: 'Analysiere zuerst eine Aufnahme', emptyHelp: 'Stelle eine Frage in natürlicher Sprache — der KI-Agent findet den Moment und antwortet mit Zitaten.', related: 'Ähnliche Videomomente', playing: 'WIEDERGABE', match: 'TREFFER', copyQuote: 'Zitat mit Zeitstempel kopieren',
    utterances: 'Segmente', ready: 'bereit zur Analyse', removeMedia: 'Medium entfernen / anderes öffnen', demoMedia: 'Demoaufnahme', teamTalk: 'Teamgespräch', loaded: 'Geladen', showTranscript: 'Vollständiges Transkript', hideTranscript: 'Transkript ausblenden', fullRecord: 'Vollständiges Transkript', generate: 'Transkript wird erstellt', runTranscription: 'Transkription starten', uploadSubs: 'Eigene Untertitel hochladen (SRT / VTT)', usingKey: 'API-Anbieter:', keyRequired: 'Für die vollständige Analyse ist ein API-Schlüssel erforderlich.', configure: 'API-Schlüssel konfigurieren', timeline: 'Momente auf der Zeitleiste', result: 'Ergebnis', playback: 'Wiedergabe',
    workflow1: 'Link oder Datei hinzufügen', workflow1s: 'YouTube, Video oder Audio', workflow2: 'Eine Frage stellen', workflow2s: 'Mit eigenen Worten', workflow3: 'Szene abspielen', workflow3s: 'Ab der genauen Sekunde', privacy: 'Private Aufnahmen. Präzise Antworten.',
    apiTitle: 'API-Schlüssel-Einstellungen', chooseProvider: 'KI- / Transkriptionsanbieter wählen:', apiKey: 'API-Schlüssel', hideKey: 'Schlüssel ausblenden', showKey: 'Schlüssel anzeigen', security: 'Dein Schlüssel wird ausschließlich in deinem Browser (localStorage) gespeichert und nie an einen Zwischenserver gesendet.', deleteKey: 'Schlüssel löschen', useDemo: 'Demo-Modus verwenden', testing: 'Schlüssel wird getestet ...', saved: 'Gespeichert!', chooseLocal: 'Lokale Transkription wählen', testSave: 'API-Schlüssel testen und speichern', close: 'Schließen',
    noKeyTitle: 'Kein API-Schlüssel konfiguriert', browserAnalysis: 'Browserbasierte Video- / Audioanalyse', noKeyText: 'Du hast noch keinen API-Schlüssel hinzugefügt. Wähle eine der beiden Optionen:', optionDemo: 'Option 1: Zum Demo-Modus wechseln (Empfohlen)', optionDemoText: 'Nutze die integrierten Demodaten, um Suche, interaktive Zeitstempel und SRT-Export zu testen.', tryDemo: 'Demo-Modus ausprobieren', optionKey: 'Option 2: API-Schlüssel eingeben', optionKeyText: 'Füge einen Schlüssel von OpenAI, Google Gemini oder Groq Cloud hinzu. Er wird nur lokal in deinem Browser gespeichert.'
  }
}

const I18nContext = createContext(null)
export function I18nProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('framefinder_language') || 'pl')
  useEffect(() => {
    localStorage.setItem('framefinder_language', language)
    document.documentElement.lang = language
    const metadata = {
      pl: ['Framefinder — znajdź właściwy moment', 'Semantyczna wyszukiwarka momentów w nagraniach wideo i audio.'],
      en: ['Framefinder — find the right moment', 'Semantic moment search for video and audio recordings.'],
      es: ['Framefinder — encuentra el momento adecuado', 'Búsqueda semántica de momentos en grabaciones de vídeo y audio.'],
      de: ['Framefinder — finde den richtigen Moment', 'Semantische Suche nach Momenten in Video- und Audioaufnahmen.']
    }[language] || []
    document.title = metadata[0]
    document.querySelector('meta[name="description"]')?.setAttribute('content', metadata[1])
  }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: key => translations[language]?.[key] ?? translations.pl[key] ?? key }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export const useI18n = () => useContext(I18nContext)
