import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  pl: {
    desktopApp: 'Aplikacja desktopowa', how: 'Jak to działa', noKey: 'Brak klucza API (Demo)', apiSettings: 'Ustawienia klucza API (BYOK)',
    kicker: 'Wyszukiwarka momentów w wideo', hero1: 'Zapytaj nagranie.', hero2: 'Znajdź właściwy kadr.', heroText: 'Wklej link YouTube lub dodaj własny plik. Opisz scenę, wypowiedź albo temat, a dostaniesz dokładny fragment.',
    youtubeFiles: 'YOUTUBE + PLIKI', natural: 'JĘZYK NATURALNY', precision: 'PRECYZJA DO SEKUNDY', youtubeLink: '01 / LINK YOUTUBE', pasteLink: 'Wklej link do filmu', directYoutube: 'Odtwarzanie bezpośrednio z YouTube', open: 'Otwórz', or: 'albo', diskFile: 'PLIK Z DYSKU', drop: 'Upuść nagranie lub wybierz plik', maxFile: 'MP4, WEBM, MP3, WAV · maks. 200 MB', demo: 'Demo',
    find: 'Znajdź moment & Odpowiedź AI', findSub: 'Agent AI przeczyta nagranie i odpowie na Twoje pytanie', searchPlaceholder: 'np. Czy Piastowie pochodzili ze Skandynawii?', clear: 'Wyczyść zapytanie', search: 'Szukaj', suggestions: 'Podpowiedzi', suggestion1: 'Czy Piastowie byli nordami?', suggestion2: 'Co badacz mówi o genetyce Słowian?', suggestion3: 'Jaki jest główny wniosek?', aiAssistant: 'ASYSTENT AI FILMU (RAG)', jump: 'Skocz do sekundy', basedAnswer: 'Odpowiedź na podstawie nagrania:', quote: 'Cytat z nagrania:', waiting: 'Materiał czeka na pytanie', analyzeFirst: 'Najpierw przeanalizuj nagranie', emptyHelp: 'Wpisz pytanie w języku naturalnym — Agent AI znajdzie moment i odpowie na pytanie w oparciu o cytaty.', related: 'Powiązane fragmenty wideo', playing: 'ODTWARZANIE', match: 'DOPASOWANIA', copyQuote: 'Kopiuj cytat ze znacznikiem czasu',
    utterances: 'wypowiedzi', ready: 'gotowy do analizy', removeMedia: 'Usuń plik / otwórz inny', demoMedia: 'Materiał demonstracyjny', teamTalk: 'rozmowa zespołu', loaded: 'Wczytano', showTranscript: 'Pełna transkrypcja', hideTranscript: 'Ukryj transkrypcję', fullRecord: 'Pełny zapis rozmowy', generate: 'Generuję transkrypcję', runTranscription: 'Uruchom transkrypcję', uploadSubs: 'Wgraj własny plik napisów (SRT / VTT)', usingKey: 'Używasz klucza API:', keyRequired: 'Wymagany klucz API do pełnej analizy nagrania.', configure: 'Skonfiguruj klucz API', timeline: 'Fragmenty na osi czasu', result: 'Wynik', playback: 'Odtwarzanie',
    workflow1: 'Dodaj link lub plik', workflow1s: 'YouTube, wideo lub audio', workflow2: 'Zadaj pytanie', workflow2s: 'Własnymi słowami', workflow3: 'Odtwórz scenę', workflow3s: 'Od właściwej sekundy', privacy: 'Prywatne nagrania. Precyzyjne odpowiedzi.',
    apiTitle: 'Ustawienia klucza API', chooseProvider: 'Wybierz dostawcę AI / Transkrypcji:', apiKey: 'Klucz API', hideKey: 'Ukryj klucz', showKey: 'Pokaż klucz', security: 'Twój klucz jest zapisywany wyłącznie w Twojej przeglądarce (localStorage). Nigdy nie jest przesyłany na żaden serwer pośredniczący.', deleteKey: 'Usuń klucz', useDemo: 'Używaj trybu Demo', testing: 'Testuję klucz...', saved: 'Zapisano!', chooseLocal: 'Wybierz transkrypcję lokalną', testSave: 'Testuj i zapisz klucz API', close: 'Zamknij',
    noKeyTitle: 'Brak skonfigurowanego klucza API', browserAnalysis: 'Przeglądarkowa analiza wideo / audio', noKeyText: 'Nie dodałeś jeszcze swojego klucza API. Możesz skorzystać z jednej z dwóch opcji:', optionDemo: 'Opcja 1: Przełącz w tryb Demo (Zalecane)', optionDemoText: 'Użyj wbudowanych danych demonstracyjnych, aby przetestować wyszukiwanie, znaczniki czasu i eksport SRT.', tryDemo: 'Wypróbuj w trybie Demo', optionKey: 'Opcja 2: Podaj swój klucz API', optionKeyText: 'Dodaj klucz OpenAI, Google Gemini lub Groq Cloud. Zostanie zapisany wyłącznie lokalnie w Twojej przeglądarce.'
  },
  en: {
    desktopApp: 'Desktop app', how: 'How it works', noKey: 'No API key (Demo)', apiSettings: 'API key settings (BYOK)',
    kicker: 'Video moment search engine', hero1: 'Ask your recording.', hero2: 'Find the right frame.', heroText: 'Paste a YouTube link or upload your own file. Describe a scene, quote, or topic to get the exact moment.',
    youtubeFiles: 'YOUTUBE + FILES', natural: 'NATURAL LANGUAGE', precision: 'SECOND-PRECISE', youtubeLink: '01 / YOUTUBE LINK', pasteLink: 'Paste a video link', directYoutube: 'Play directly from YouTube', open: 'Open', or: 'or', diskFile: 'FILE FROM DISK', drop: 'Drop a recording or choose a file', maxFile: 'MP4, WEBM, MP3, WAV · max. 200 MB', demo: 'Demo',
    find: 'Find a moment & AI answer', findSub: 'The AI agent reads the recording and answers your question', searchPlaceholder: 'e.g. What is the main conclusion?', clear: 'Clear query', search: 'Search', suggestions: 'Suggestions', suggestion1: 'What is the main topic?', suggestion2: 'What does the speaker say about the research?', suggestion3: 'What is the main conclusion?', aiAssistant: 'VIDEO AI ASSISTANT (RAG)', jump: 'Jump to time', basedAnswer: 'Answer based on the recording:', quote: 'Quote from the recording:', waiting: 'The recording is ready for a question', analyzeFirst: 'Analyze a recording first', emptyHelp: 'Ask a question in natural language — the AI agent will find the moment and answer using quotes.', related: 'Related video moments', playing: 'PLAYING', match: 'MATCH', copyQuote: 'Copy quote with timestamp',
    utterances: 'segments', ready: 'ready to analyze', removeMedia: 'Remove media / open another', demoMedia: 'Demo recording', teamTalk: 'team conversation', loaded: 'Loaded', showTranscript: 'Full transcript', hideTranscript: 'Hide transcript', fullRecord: 'Full transcript', generate: 'Generating transcript', runTranscription: 'Start transcription', uploadSubs: 'Upload your own subtitles (SRT / VTT)', usingKey: 'API provider:', keyRequired: 'An API key is required for full recording analysis.', configure: 'Configure API key', timeline: 'Moments on the timeline', result: 'Result', playback: 'Playback',
    workflow1: 'Add a link or file', workflow1s: 'YouTube, video, or audio', workflow2: 'Ask a question', workflow2s: 'In your own words', workflow3: 'Play the scene', workflow3s: 'From the exact second', privacy: 'Private recordings. Precise answers.',
    apiTitle: 'API key settings', chooseProvider: 'Choose an AI / transcription provider:', apiKey: 'API key', hideKey: 'Hide key', showKey: 'Show key', security: 'Your key is stored only in your browser (localStorage). It is never sent to an intermediary server.', deleteKey: 'Delete key', useDemo: 'Use Demo mode', testing: 'Testing key...', saved: 'Saved!', chooseLocal: 'Choose local transcription', testSave: 'Test and save API key', close: 'Close',
    noKeyTitle: 'No API key configured', browserAnalysis: 'Browser-based video / audio analysis', noKeyText: 'You have not added an API key yet. Choose one of these two options:', optionDemo: 'Option 1: Switch to Demo mode (Recommended)', optionDemoText: 'Use built-in demo data to test search, interactive timestamps, and SRT export.', tryDemo: 'Try Demo mode', optionKey: 'Option 2: Enter your API key', optionKeyText: 'Add an OpenAI, Google Gemini, or Groq Cloud key. It will be stored only in your browser.'
  }
}

const I18nContext = createContext(null)
export function I18nProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('framefinder_language') || 'pl')
  useEffect(() => {
    localStorage.setItem('framefinder_language', language)
    document.documentElement.lang = language
    document.title = language === 'pl' ? 'Framefinder — znajdź właściwy moment' : 'Framefinder — find the right moment'
    document.querySelector('meta[name="description"]')?.setAttribute('content', language === 'pl' ? 'Semantyczna wyszukiwarka momentów w nagraniach wideo i audio.' : 'Semantic moment search for video and audio recordings.')
  }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: key => translations[language]?.[key] ?? translations.pl[key] ?? key }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export const useI18n = () => useContext(I18nContext)
